version: "3"

services:

  rabbit_mq:
    image: rabbitmq:3.10.7-management
    container_name: rabbit_mq
    hostname: rabbitmq
    restart: always
    ports:
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  producer:
    build: producer
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/usr/src/app/producer

volumes:
    rabbit_mqdata:
      driver: local
